# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Han Shiyu"
title_separator          : "-"
name                     : &name "Han Shiyu"
description              : &description "personal description"
url                      :  "https://Han-Shiyu.github.io"



# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "zhengjian.png"
  name             : "Han Shiyu"
  bio              : "Master's degree student,School of Management,Zhengzhou Univeisity"
  location         : "China Zhengzhou"
  uri              :  "https://Han-Shiyu.github.io"


 
